Repository manankohlii/spacex-launch-data, pull requests merged in 2021-06, with the labels that each got.

#26 added card structure with styles & animation for mission details
  index.html
  main.css
  main.js
Labels: LGMSOC21, level3

#25 Button design and trigger function
  README.md
  index.html
  main.css
  main.js
Labels: LGMSOC21, level2

#33 handling mission out of range available input
  main.js
Labels: LGMSOC21, 🟨 Level2

#46 made website completely responsive!
  index.html
  main.css
Labels: LGMSOC21, 🟧 Level3

#49 Issue & PR templates added
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: LGMSOC21, 🟩 Level1

#44 Added mission patch images (Issue #38)
  index.html
  main.css
  main.js
Labels: LGMSOC21, 🟧 Level3

#54 Added shields.io features and spacex api info to README.md
  README.md
Labels: LGMSOC21, 🟨 Level2

#62 Updated README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#58 Added particles.js in background
  app.js
  bg1.png
  index.html
  main.css
  particles.js
Labels: LGMSOC21, 🟨 Level2

#64 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: LGMSOC21, 🟩 Level1

#66 footer-added
  index.html
  main.css
Labels: LGMSOC21, 🟨 Level2

#71 Reformat Code Structure
  README.md
  images/bg1.png
  images/bg3.jpg
  images/fav.png
  index.html
  js/app.js
  js/main.js
  js/particles.js
  main.css
Labels: LGMSOC21, 🟨 Level2

#74 Footer added
  index.html
  main.css
Labels: LGMSOC21, 🟨 Level2

#76 social media icons opening in new tab
  index.html
Labels: LGMSOC21, 🟩 Level1

#83 added popup video onclick feature
  index.html
  js/main.js
  main.css
Labels: LGMSOC21, 🟧 Level3

#87 Title box border animation added...
  index.html
  main.css
Labels: LGMSOC21, 🟨 Level2

#92 Added Open Source Program Section #91
  README.md
Labels: LGMSOC21, 🟩 Level1

#88 Added Navbar
  index.html
  js/main.js
  main.css
Labels: LGMSOC21, 🟧 Level3

#99 modification on nav #98
  index.html
  js/main.js
  main.css
Labels: LGMSOC21, 🟨 Level2

#97 Reset Search box content
  js/main.js
Labels: LGMSOC21, 🟩 Level1

#101 issue #100 Logo addition
  .DS_Store
  images/.DS_Store
  images/logoSpaceXMK.png
  index.html
  main.css
Labels: LGMSOC21, 🟥 Level4

#104 Automatic Updation of Footer Copyright Year
  index.html
Labels: LGMSOC21, 🟩 Level1

#106 Minor changes
  README.md
Labels: LGMSOC21, 🟪 Level0

#107 Navbar responsive
  index.html
  js/main.js
  main.css
Labels: LGMSOC21, 🟧 Level3

#113 Removing Insecure links
  index.html
Labels: LGMSOC21, 🟩 Level1

#116 pre loader added
  index.html
  js/main.js
  ll3.gif
  main.css
Labels: LGMSOC21, 🟧 Level3

#121 scroll to top button
  index.html
  js/scroll.js
  main.css
Labels: LGMSOC21, 🟨 Level2

#127 3D effect added to mission logo
  index.html
  js/vanilla-tilt.js
Labels: LGMSOC21, 🟨 Level2
